<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Beta</name>
   <tag></tag>
   <elementGuidId>2d6cc677-c9f9-4669-a07f-a1b3d549fb98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='class-summary.tabpanel']/div/div[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;annotation interface in org.openqa.selenium&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>37a9cf9e-57de-40fb-bce3-320246dba118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Beta.html</value>
      <webElementGuid>b4928b9a-aa2c-401b-a5c3-7c7a49ff5810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>annotation interface in org.openqa.selenium</value>
      <webElementGuid>bcd128cf-da66-41e3-a2b2-813b8fd5e566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beta</value>
      <webElementGuid>47e24cfd-828c-45ae-b856-be966bc0678b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class-summary.tabpanel&quot;)/div[@class=&quot;summary-table two-column-summary&quot;]/div[@class=&quot;col-first odd-row-color class-summary class-summary-tab7&quot;]/a[1]</value>
      <webElementGuid>1115dcfe-0bed-49fc-a3b8-6988c5064dee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='class-summary.tabpanel']/div/div[9]/a</value>
      <webElementGuid>c4486915-abb7-4fdb-beb6-61a5616979ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Beta')]</value>
      <webElementGuid>0e400e94-f33c-41ff-834b-e966b0466ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Represents the known architectures used in WebDriver.'])[1]/following::a[1]</value>
      <webElementGuid>e486fcce-11d7-46c8-9d7c-438bbc04ad20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Architecture'])[1]/following::a[1]</value>
      <webElementGuid>61881d2a-dfa2-466c-b2ca-a038f30a1eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indicates that a feature or API is in active development, and so should not be relied upon.'])[1]/preceding::a[1]</value>
      <webElementGuid>d85585fa-e1eb-4eec-81bd-289967cf24d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BuildInfo'])[1]/preceding::a[1]</value>
      <webElementGuid>3c33c6be-c572-40a4-85be-8791e0fedda0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beta']/parent::*</value>
      <webElementGuid>daab413a-1f24-42a0-a2f5-f95a858b5522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Beta.html')]</value>
      <webElementGuid>377bf1b5-135c-4476-bb5b-e5150ebceea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/a</value>
      <webElementGuid>90816a66-951d-4f5d-8be6-974a49cad7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Beta.html' and @title = 'annotation interface in org.openqa.selenium' and (text() = 'Beta' or . = 'Beta')]</value>
      <webElementGuid>a6ae3f8b-22d6-4aab-9cd7-84c6e2072095</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
