<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_86_mw-file-element</name>
   <tag></tag>
   <elementGuidId>60b72237-e9eb-46e3-9a8f-7aae88b001fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/div[8]/div/div/div/div/span/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ba508156-d4e5-44a3-ac8b-858a0fb77099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Orcas_in_Punta_Norte_Valdes_Peninsula_-_panoramio.jpg/200px-Orcas_in_Punta_Norte_Valdes_Peninsula_-_panoramio.jpg</value>
      <webElementGuid>3ba96a87-d33b-46c5-a3b6-0b1fab35dec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>c9957f90-9481-43d4-b34b-a8675dd5ca6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>e5c1e7e2-97c0-42f8-b8a2-712278185d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>108</value>
      <webElementGuid>f7a82dab-1b9e-4ad1-a722-5263ec002d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mw-file-element</value>
      <webElementGuid>b8484121-8752-4a64-8614-10427589d1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>//upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Orcas_in_Punta_Norte_Valdes_Peninsula_-_panoramio.jpg/300px-Orcas_in_Punta_Norte_Valdes_Peninsula_-_panoramio.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Orcas_in_Punta_Norte_Valdes_Peninsula_-_panoramio.jpg/400px-Orcas_in_Punta_Norte_Valdes_Peninsula_-_panoramio.jpg 2x</value>
      <webElementGuid>48b4dbbe-0b08-46e9-a5f7-dd3b83182266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-file-width</name>
      <type>Main</type>
      <value>900</value>
      <webElementGuid>4a0e80a0-7513-4d3e-889c-b96ad04e8fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-file-height</name>
      <type>Main</type>
      <value>484</value>
      <webElementGuid>d4f4cbb7-b265-4a46-89c5-610a84d3d28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/div[@class=&quot;thumb tmulti tright&quot;]/div[@class=&quot;thumbinner multiimageinner&quot;]/div[@class=&quot;trow&quot;]/div[@class=&quot;tsingle&quot;]/div[@class=&quot;thumbimage&quot;]/span[1]/a[@class=&quot;mw-file-description&quot;]/img[@class=&quot;mw-file-element&quot;]</value>
      <webElementGuid>1f344354-727b-4e2e-a412-96df477b7181</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/div[8]/div/div/div/div/span/a/img</value>
      <webElementGuid>67d7d373-aa3b-4f1f-bec1-0b9ada512488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/span/a/img</value>
      <webElementGuid>6df08c43-c79d-49d1-91e9-04c4d4cdafbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Orcas_in_Punta_Norte_Valdes_Peninsula_-_panoramio.jpg/200px-Orcas_in_Punta_Norte_Valdes_Peninsula_-_panoramio.jpg']</value>
      <webElementGuid>6b970c36-4a58-47a6-af38-ff5087c73428</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
