<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Upload file_vector-icon mw-ui-icon-sea_526750</name>
   <tag></tag>
   <elementGuidId>cd169e10-4396-4d63-b716-736addfceed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p-search']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.vector-icon.mw-ui-icon-search.mw-ui-icon-wikimedia-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>430cf930-86c9-4998-b163-d98f15622323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search</value>
      <webElementGuid>5b266756-55ad-448d-9a46-eba6c7456cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-search&quot;)/a[@class=&quot;cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle&quot;]/span[@class=&quot;vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search&quot;]</value>
      <webElementGuid>6279f1e6-23cb-4976-9a33-a404144af445</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-search']/a/span</value>
      <webElementGuid>a1a4049d-c523-4055-a5e6-641f244277ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span</value>
      <webElementGuid>59a87b91-0041-435d-893a-ebf0ad640012</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
