<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Orca</name>
   <tag></tag>
   <elementGuidId>42a4ecf9-86a6-4e0d-9d08-749047c7a307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='cdx-menu-item-12']/a/span[2]/span/bdi/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.cdx-search-result-title__match</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>57868716-b599-4748-9491-633da33207a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cdx-search-result-title__match</value>
      <webElementGuid>9cfbe753-f1db-420c-99e1-606808868edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Orca</value>
      <webElementGuid>1ca93769-fd14-455b-a8c9-b8713c2ff353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdx-menu-item-12&quot;)/a[@class=&quot;cdx-menu-item__content&quot;]/span[@class=&quot;cdx-menu-item__text&quot;]/span[@class=&quot;cdx-search-result-title&quot;]/bdi[1]/span[@class=&quot;cdx-search-result-title__match&quot;]</value>
      <webElementGuid>7890a2a3-6d25-41da-97ed-a5839811eed0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='cdx-menu-item-12']/a/span[2]/span/bdi/span</value>
      <webElementGuid>6db5c317-4403-44d0-9dc5-0515c21a1e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::span[6]</value>
      <webElementGuid>6bbce43b-fc09-49a1-8c89-5ba5c50662aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload file'])[1]/following::span[9]</value>
      <webElementGuid>48f01b6e-ce77-44a2-bea2-9eb26c07fb69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Largest living species of dolphin'])[1]/preceding::span[1]</value>
      <webElementGuid>b90d003a-d7d9-4ec8-b731-bf1e553d63ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Orca']/parent::*</value>
      <webElementGuid>bf363f8f-6277-41c7-b408-dd7484dd3256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bdi/span</value>
      <webElementGuid>073304ce-b70e-4126-af36-2da724fea761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Orca' or . = 'Orca')]</value>
      <webElementGuid>955da5ad-f78a-4b73-acd5-883538932a5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
