<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Overview</name>
   <tag></tag>
   <elementGuidId>06c2da63-a6ba-48d5-ab7e-e5879cf411df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='navbar-top-firstrow']/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b748dfce-c5ef-4bcc-9c42-2fac9a60152f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../../../index.html</value>
      <webElementGuid>5cf0c81a-c88d-4af4-8f15-f42549c75178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Overview</value>
      <webElementGuid>f52cc362-0d03-419f-ae64-bb3144925c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar-top-firstrow&quot;)/li[1]/a[1]</value>
      <webElementGuid>7dbc39bf-7c90-4638-af31-9093f1d640a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='navbar-top-firstrow']/li/a</value>
      <webElementGuid>ad8c7cef-70c3-4c45-ac58-c0c022cd0954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Overview')]</value>
      <webElementGuid>7ecacfdf-e778-4942-bada-44440775f2e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip navigation links'])[1]/following::a[1]</value>
      <webElementGuid>2d1fb170-96d3-4a40-9740-8d013d4e3c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Package'])[1]/preceding::a[1]</value>
      <webElementGuid>3e160358-04c3-4f81-a32c-e450e96cc646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class'])[1]/preceding::a[2]</value>
      <webElementGuid>9b22ba84-115f-46d3-8659-636f3da9810a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Overview']/parent::*</value>
      <webElementGuid>10d1e50e-7658-42fe-9ae4-19e0eafe92e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../../../index.html')]</value>
      <webElementGuid>54e05f91-7b94-4670-9082-dc58e2d7b1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>d97c65f4-e085-4528-b52e-b6597b6f0f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../../../index.html' and (text() = 'Overview' or . = 'Overview')]</value>
      <webElementGuid>c15caf98-29c6-45d7-8eda-755b510e6efa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
